"""empty message

Revision ID: 69ebbc091b9e
Revises: 3c8f1d986f63
Create Date: 2021-02-16 03:57:22.801039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ebbc091b9e'
down_revision = '3c8f1d986f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('style', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'style')
    # ### end Alembic commands ###
