"""empty message

Revision ID: 7d9193a8e74e
Revises: 69ebbc091b9e
Create Date: 2021-02-19 10:21:04.797995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9193a8e74e'
down_revision = '69ebbc091b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile')
    # ### end Alembic commands ###
